name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
   
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.6.0
      - name: build node project
        run: |
          npm install
          npm run build
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v2.4.1
      - name: build node project
        run: docker build -t deployment .
      - name: "Configure AWS Credentials" 
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESSKEY}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: ap-south-1
      - name: login to aws ecr
        run: aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 815464048229.dkr.ecr.ap-south-1.amazonaws.com
      - name: docker image push
        run: |
          docker tag deployment:latest 815464048229.dkr.ecr.ap-south-1.amazonaws.com/learning-deployment:latest
          docker push 815464048229.dkr.ecr.ap-south-1.amazonaws.com/learning-deployment:latest
        
          
        
